# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  scrollHeight: 8
  sidePanelWidth: 0.25
  mainPanelSplitMode: vertical
  showListFooter: false
  showFileTree: false
  showRandomTip: true
  showCommandLog: true
  showBottomLine: true
  showPanelJumps: false
  nerdFontsVersion: "3"
  commitHashLength: 8
  showBranchCommitHash: true
  showDivergenceFromBaseBranch: arrowAndNumber
  commandLogSize: 4
  splitDiff: auto
  filterMode: fuzzy
  statusPanelView: dashboard
  switchToFilesAfterStashPop: true
  switchToFilesAfterStashApply: false

  # Tokyonight Storm
  # ref: https://github.com/folke/tokyonight.nvim/blob/main/extras/lazygit/tokyonight_storm.yml
  theme:
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#29a4bd"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#2e3c64"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"

git:
  paging:
    colorArg: always
    pager: >-
      delta --paging=never \
            --color-only   \
            --hyperlinks   \
            --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  commit:
    autoWrapWidth: 80
  parseEmoji: true
  log:
    showWholeGraph: true
  truncateCopiedCommitHashesTo: 12

confirmOnQuit: true

os:
  editPreset: nvim-remote

disableStartupPopups: false
promptToReturnFromSubprocess: false
