# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  scrollHeight: 8
  sidePanelWidth: 0.25
  mainPanelSplitMode: vertical
  showListFooter: false
  showFileTree: false
  showRandomTip: true
  showCommandLog: true
  showBottomLine: true
  showPanelJumps: false
  nerdFontsVersion: "3"
  commitHashLength: 8
  showBranchCommitHash: true
  showDivergenceFromBaseBranch: arrowAndNumber
  commandLogSize: 4
  splitDiff: auto
  filterMode: fuzzy
  statusPanelView: dashboard
  switchToFilesAfterStashPop: true
  switchToFilesAfterStashApply: false
