# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

# Config relating to the Lazygit UI
gui:
  # The number of lines you scroll by when scrolling the main window
  scrollHeight: 8

  # Fraction of the total screen width to use for the left side section
  # Number from 0 to 1.0
  sidePanelWidth: 0.25

  # Sometimes the main window is split in two (e.g. when the selected file has both staged and unstaged changes)
  # This setting controls how the two sections are split
  mainPanelSplitMode: vertical

  # If true, show the '5 of 20' footer at the bottom of list views
  showListFooter: false

  # If true, display the files in the file views as a tree
  # If false, display the files as a flat list
  # This can be toggled from within Lazygit with the '~' key, but that will not change the default
  showFileTree: true

  # If true, show a random tip in the command log when Lazygit starts
  showRandomTip: true

  # If true, show the command log
  showCommandLog: true

  # If true, show the bottom line that contains keybinding info and useful buttons
  # If false, this line will be hidden except to display a loader for an in-progress action
  showBottomLine: true

  # If true, show jump-to-window keybindings in window titles
  showPanelJumps: false

  # Nerd fonts version to use
  # One of: '2' | '3' | empty string (default)
  nerdFontsVersion: "3"

  # Length of commit hash in commits view
  commitHashLength: 8

  # If true, show commit hashes alongside branch names in the branches view
  showBranchCommitHash: true

  # Whether to show the divergence from the base branch in the branches view
  showDivergenceFromBaseBranch: arrowAndNumber

  # Height of the command log view
  commandLogSize: 4

  # Whether to split the main window when viewing file changes
  # If 'auto', only split the main window when a file has both staged and unstaged changes
  splitDiff: auto

  # How things are filtered when typing '/'
  filterMode: fuzzy

  # Status panel view
  statusPanelView: dashboard

  # If true, jump to the Files panel after popping a stash
  switchToFilesAfterStashPop: true

  # If true, jump to the Files panel after applying a stash
  switchToFilesAfterStashApply: false
