#!/bin/zsh

#** fix AWK error "illegal byte sequence"
#** ref: https://stackoverflow.com/questions/19242275/re-error-illegal-byte-sequence-on-mac-os-x
export LANG=C
export LC_CTYPE=C

#** If you come from bash you might have to change your $PATH.
# export PATH="$PATH"

#** Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

#** Set name of the theme to load. Optionally, if you set this to "random"
#** it'll load a random theme each time that oh-my-zsh is loaded.
#** See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="af-magic"

#** Set list of themes to load
#** Setting this variable when "ZSH_THEME=random"
#** cause zsh load theme from this variable instead of
#** looking in "~/.oh-my-zsh/themes/"
#** An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

#** use case-sensitive completion.
# CASE_SENSITIVE="true"

#** use hyphen-insensitive completion. Case sensitive completion
#** must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

#** disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

#** change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

#** disable colors in ls.
# DISABLE_LS_COLORS="true"

#** disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

#** enable command auto-correction.
# ENABLE_CORRECTION="true"

#** display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

#** disable marking untracked files under VCS as dirty.
#** This makes repository status check for large repositories
#** much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

#** change the command execution time
#** stamp shown in the history command output.
#** The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

#** Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

#** Which plugins would you like to load?
#** (plugins can be found in ~/.oh-my-zsh/plugins/*)
#** Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
#** Example format: plugins=(rails git textmate ruby lighthouse)
#** Add wisely, as too many plugins slow down shell startup.
plugins=(
  colored-man-pages
  docker
  encode64 #** encode64 ... <-> decode64 ...
  git
  jsontools #** pp_json, is_json, urlencode_json, urldecode_json
  node
  npm
  pip
  python
  yarn
)

source "$ZSH/oh-my-zsh.sh"
source "$(brew --prefix asdf)/libexec/asdf.sh"
source "$HOME/.asdf/plugins/golang/set-env.zsh"
