[cd]
  command = "nu"

[diff]
  command = "nvim"
  args = ["-d", "{{ .Target }}", "{{ .Destination }}"]
  exclude = ["scripts", "externals"]

[edit]
  command = "nvim"

[[textconv]]
  command = "plutil"
  args = ["-convert", "xml1", "-o", "-", "-"]
  pattern = "**/*.plist"
