package:
  mise:
    - bun
    - go
    - lua@5.1
    - nodejs
    - pipx
    - python

  python:
    - neovim-remote

  npm:
    - "@fission-ai/openspec"
    - skills
    - tree-sitter-cli
    - typescript

  go:
    - github.com/mitranim/gow

  yazi:
    - 956MB/vscode-dark-plus
    - BennyOe/tokyo-night
    - gosxrgxx/flexoki-dark
    - yazi-rs/plugins:smart-paste
    - yazi-rs/plugins:types
