package:
  mise:
  - bun
  - go
  - lua@5.1
  - nodejs
  - python

  python:
  - neovim-remote

  npm:
  - typescript

  go:
  - github.com/mitranim/gow

  yazi:
  - BennyOe/tokyo-night
  - gosxrgxx/flexoki-dark
  - 956MB/vscode-dark-plus
  - yazi-rs/plugins:smart-paste
  - yazi-rs/plugins:types
