# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# This is the list of prompt-wide configuration options
# ref: https://starship.rs/config/#prompt
command_timeout = 1000

[docker_context]
  disabled = true

[elixir]
  disabled = true

[custom.elixir]
  description = "The currently installed versions of Elixir and OTP"
  format = 'via [$symbol( v$output) ]($style)'
  symbol = '💧'
  style = 'bold purple'
  command = """mise current elixir | split row '-' | $"($in.0) \\(OTP ($in.2 | str trim)\\)""""
  detect_files = ['mix.exs']
