modelRoles:
  default: openai-codex/gpt-6.1-sol:high
  smol: openai-codex/gpt-6-luna:xhigh
  slow: openai-codex/gpt-6-astra:medium
  task: openai-codex/gpt-6.1-sol:medium
  advisor: openai-codex/gpt-6-astra:medium
  tiny: openai-codex/gpt-6-luna:medium
  memory: openai-codex/gpt-6-luna:high
  plan: openai-codex/gpt-6.1-sol:xhigh
  vision: tuxevil-rotator/gemini-3.8-flash-high:off
  commit: tuxevil-rotator/gemini-3.8-flash-low:off
symbolPreset: nerd
composer:
  shape: claude
  tokenRate: true
theme:
  dark: dark-tundra
  light: dark-tundra
setupVersion: 2
statusLine:
  preset: custom
  leftSegments:
    - pi
    - vim
    - model
    - mode
    - collab
    - stream
    - pr
    - context_tokens
    - status
  rightSegments:
    - session_name
  compactThinkingLevel: true
  showHookStatus: false
terminal:
  showProgress: true
tui:
  textSizing: true
display:
  hideToolActivity: true
hideThinkingBlock: true
cycleOrder:
  - default
  - smol
  - slow
dev:
  autoqaConsent: granted
disabledProviders:
  - claude
  - claude-plugins
  - codex
  - gemini
  - opencode
commands:
  enableOpencodeProject: false
  enableClaudeProject: false
retry:
  waitForUsageReset: true
  fallbackChains:
    tiny:
      - tuxevil-rotator/gemini-3.8-flash-low
    smol:
      - tuxevil-rotator/gemini-3.8-flash-high
    default:
      - tuxevil-rotator/gemini-3.1-pro-low
    slow:
      - tuxevil-rotator/gemini-3.1-pro-high
    plan:
      - tuxevil-rotator/gemini-3.1-pro-high
    memory:
      - tuxevil-rotator/gemini-3.8-flash-high
    advisor:
      - tuxevil-rotator/gemini-3.1-pro-high
    task:
      - tuxevil-rotator/gemini-3.1-pro-low
title:
  icons: boring
  generator: tiny
steeringMode: all
followUpMode: all
interruptMode: wait
treeFilterMode: no-tools
completion:
  notify: "off"
error:
  notify: "on"
recap:
  idleSeconds: 600
collab:
  displayName: krikchaip
features:
  unexpectedStopDetection: smart
extendedContext: true
compaction:
  methodOrder:
    - snapcompact
    - handoff
  thresholdPercent: 50
  modelThresholds:
    openai-codex/gpt-6-astra: 300000
    openai-codex/gpt-6-luna: 300000
    openai-codex/gpt-6.1-sol: 300000
    tuxevil-rotator/gemini-3.1-pro-high: 300000
    tuxevil-rotator/gemini-3.1-pro-low: 300000
    tuxevil-rotator/gemini-3.8-flash-high: 300000
    tuxevil-rotator/gemini-3.8-flash-low: 300000
snapcompact:
  toolResults: true
read:
  renderMarkdown: true
  toolResultPreview: true
lsp:
  formatOnWrite: true
  diagnosticsOnEdit: true
bash:
  allowCompoundCommands: true
todo:
  enabled: false
astGrep:
  enabled: true
generate_image:
  enabled: true
browser:
  enabled: false
plan:
  autosave: true
