# tmux seems to lost this keymap halfway, so I remapped it
bind -n C-S-Space send Escape "[32;6u"

bind -n -N "[Window] Goto last" M-BTab last-window

bind -n -N "[Pane] Switch to left"  C-M-h if -F '#{window_zoomed_flag}' 'select-pane -Z -L' 'select-pane -L'
bind -n -N "[Pane] Switch to below" C-M-j if -F '#{window_zoomed_flag}' 'select-pane -Z -D' 'select-pane -D'
bind -n -N "[Pane] Switch to above" C-M-k if -F '#{window_zoomed_flag}' 'select-pane -Z -U' 'select-pane -U'
bind -n -N "[Pane] Switch to right" C-M-l if -F '#{window_zoomed_flag}' 'select-pane -Z -R' 'select-pane -R'
bind -n -N "[Pane] Switch to last"  M-Tab if -F '#{window_zoomed_flag}' 'last-pane -Z' 'last-pane'

# vim:ft=tmux.chezmoitmpl
