#!/bin/bash

#** XML template for com.apple.symbolichotkeys -> AppleSymbolicHotKeys
function key-disable() {
  local TEMPLATE="<dict><key>enabled</key><false/></dict>"
  echo "$TEMPLATE"
}

#** XML template for com.apple.symbolichotkeys -> AppleSymbolicHotKeys
function key-combo() {
  local TEMPLATE="
    <dict>
      <key>enabled</key><true/>
      <key>value</key><dict>
        <key>type</key><string>standard</string>
        <key>parameters</key>
        <array>
          <integer>$1</integer>
          <integer>$2</integer>
          <integer>$3</integer>
        </array>
      </dict>
    </dict>
  "
  echo "$TEMPLATE"
}

#**************************************************************#
#***************** [Global Configurations] ********************#
#**************************************************************#

#** Appearance > Appearance = Dark
defaults write -g AppleInterfaceStyle Dark

#** Accessibility > Display > Reduce motion = ✅
defaults write com.apple.universalaccess reduceMotion -bool true

#** Accessibility > Pointer Control > Double-click speed
defaults write -g com.apple.mouse.doubleClickThreshold -float 0.5

#** Accessibility > Pointer Control > Sprint-loading = ✅
defaults write -g com.apple.springing.enabled -bool true

#** Accessibility > Pointer Control > Sprint-loading speed
defaults write -g com.apple.springing.delay -float 0.5

#** Desktop & Dock > Dock > Size
defaults write com.apple.dock tilesize -int 27

#** Desktop & Dock > Dock > Magnification
defaults write com.apple.dock largesize -int 16

#** Desktop & Dock > Dock > Position on screen
defaults write com.apple.dock orientation left

#** Desktop & Dock > Dock > Minimize windows into application icon
defaults write com.apple.dock minimize-to-application -bool false

#** Desktop & Dock > Dock > Show indicators for open applications
defaults write com.apple.dock show-process-indicators -bool true

#** Desktop & Dock > Mission Control > Automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

#** Desktop & Dock > Mission Control > Switch to a space with open windows for the application
defaults write -g AppleSpacesSwitchOnActivate -bool false

#** Desktop & Dock > Mission Control > Displays have separate Spaces
defaults write com.apple.spaces spans-displays -bool false

#** Keyboard > Key repeat rate
defaults write -g KeyRepeat -float 2

#** Keyboard > Delay until repeat
defaults write -g InitialKeyRepeat -float 15

#** Keyboard > Touch Bar Settings > Touch Bar Shows = App Controls & Show Control Strip = ✅
defaults write com.apple.touchbar.agent PresentationModeGlobal appWithControlStrip

#** Keyboard > Touch Bar Settings > Press and hold fn key to = Show F# keys
defaults write com.apple.touchbar.agent PresentationModeFnModes -dict-add "appWithControlStrip" -string "functionKeys"

#** Keyboard > Touch Bar Settings > Show typing suggestions
defaults write -g NSAutomaticTextCompletionEnabled -bool false

#** Keyboard > Touch Bar Settings > Customize Control Strip...
defaults write com.apple.controlstrip MiniCustomized -array \
  "com.apple.system.show-desktop"
defaults write com.apple.controlstrip FullCustomized -array \
  "com.apple.system.group.brightness" \
  "NSTouchBarItemIdentifierFlexibleSpace" \
  "com.apple.system.mission-control" \
  "com.apple.system.launchpad" \
  "NSTouchBarItemIdentifierFlexibleSpace" \
  "com.apple.system.screencapture" \
  "com.apple.system.sleep" \
  "NSTouchBarItemIdentifierFlexibleSpace" \
  "com.apple.system.group.media" \
  "com.apple.system.group.volume"

#** Keyboard > Keyboard Shortcuts... > Launchpad & Dock > Turn Dock hiding on/off = ❌
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 52 "$(key-disable)"

#** Keyboard > Keyboard Shortcuts... > Launchpad & Dock > Show Launchpad = ❌
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 160 "$(key-disable)"

#** Keyboard > Keyboard Shortcuts... > Display > Decrease display brightness = ❌
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 53 "$(key-disable)"

#** Keyboard > Keyboard Shortcuts... > Display > Increase display brightness = ❌
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 54 "$(key-disable)"

#** Keyboard > Keyboard Shortcuts... > Mission Control > Mission Control = ctrl + k
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 32 "$(key-combo 107 40 262144)"

#** Keyboard > Keyboard Shortcuts... > Mission Control > Application windows = ctrl + j
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 33 "$(key-combo 106 38 262144)"

#** Keyboard > Keyboard Shortcuts... > Mission Control > Show Desktop = F11
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 36 "$(key-combo 65535 103 8388608)"

#** Keyboard > Keyboard Shortcuts... > Mission Control > Move left a space = ctrl + h
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 79 "$(key-combo 104 4 262144)"

#** Keyboard > Keyboard Shortcuts... > Mission Control > Move right a space = ctrl + l
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 81 "$(key-combo 108 37 262144)"

#** Keyboard > Keyboard Shortcuts... > Mission Control > Switch to Desktop 1 = ctrl + 1
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 118 "$(key-combo 65535 18 262144)"

#** Keyboard > Keyboard Shortcuts... > Mission Control > Switch to Desktop 2 = ctrl + 2
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 119 "$(key-combo 65535 19 262144)"

#** Keyboard > Keyboard Shortcuts... > Mission Control > Switch to Desktop 3 = ctrl + 3
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 120 "$(key-combo 65535 20 262144)"

#** Keyboard > Keyboard Shortcuts... > Mission Control > Switch to Desktop 4 = ctrl + 4
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 121 "$(key-combo 65535 21 262144)"

#** Keyboard > Keyboard Shortcuts... > Mission Control > Switch to Desktop 5 = ctrl + 5
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 122 "$(key-combo 65535 23 262144)"

#** Keyboard > Keyboard Shortcuts... > Mission Control > Switch to Desktop 6 = ctrl + 6
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 123 "$(key-combo 65535 22 262144)"

#** Keyboard > Keyboard Shortcuts... > Mission Control > Switch to Desktop 7 = ctrl + 7
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 124 "$(key-combo 65535 26 262144)"

#** Keyboard > Keyboard Shortcuts... > Mission Control > Switch to Desktop 8 = ctrl + 8
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 125 "$(key-combo 65535 28 262144)"

#** Keyboard > Keyboard Shortcuts... > Mission Control > Switch to Desktop 9 = ctrl + 9
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 126 "$(key-combo 65535 25 262144)"

#** Keyboard > Keyboard Shortcuts... > Keyboard > Change the way Tab moves focus = ❌
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 13 "$(key-disable)"

#** Keyboard > Keyboard Shortcuts... > Keyboard > Turn keyboard access on or off = ❌
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 12 "$(key-disable)"

#** Keyboard > Keyboard Shortcuts... > Keyboard > Move focus to the menu bar = ctrl + cmd + shift + h
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 7 "$(key-combo 104 4 1441792)"

#** Keyboard > Keyboard Shortcuts... > Keyboard > Move focus to the Dock = ❌
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 8 "$(key-disable)"

#** Keyboard > Keyboard Shortcuts... > Keyboard > Move focus to active or next window = ❌
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 9 "$(key-disable)"

#** Keyboard > Keyboard Shortcuts... > Keyboard > Move focus to the window toolbar = ❌
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 10 "$(key-disable)"

#** Keyboard > Keyboard Shortcuts... > Keyboard > Move focus to the floating window = ❌
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 11 "$(key-disable)"

#** Keyboard > Keyboard Shortcuts... > Keyboard > Move focus to next window = cmd + `
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 27 "$(key-combo 96 50 1048576)"

#** Keyboard > Keyboard Shortcuts... > Keyboard > Move focus to status menu = ctrl + cmd + shift + l
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 57 "$(key-combo 108 37 1441792)"

#**************************************************************#
#*************** [Application Configurations] *****************#
#**************************************************************#

#** enable repeat keys for VSCode (Vim extension)
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
