#!/bin/bash

#** install homebrew
bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew bundle --no-lock --file=/dev/stdin <<-EOF
	#** adds more repos to the list of formulae
	#** that brew tracks, updates, and installs from
	tap "homebrew/cask-fonts"
	tap "koekeishiya/formulae"

	#** brew formulae
	brew "asdf"
	brew "bat"
	brew "dive"
	brew "jq"
	brew "shellcheck"
	brew "shfmt"
	brew "skhd"
	brew "yabai"

	#** brew cask applications
	cask "1password"
	cask "dbeaver-community"
	cask "displaylink"
	cask "docker"
	cask "font-fira-code"
	cask "google-chrome"
	cask "google-drive"
	cask "insomnia"
	cask "karabiner-elements"
	cask "notion"
	cask "numi"
	cask "shortcat"
	cask "spacelauncher"
	cask "visual-studio-code"
EOF

#** start yabai & skhd on background
#** NOTE: to disable SIP (System Integrity Protection) please follows the link below
#** https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection
yabai --start-service && skhd --start-service
[[ $(arch) == *"arm"* ]] && (csrutil status | grep -qv 'enabled') && sudo nvram boot-args=-arm64e_preview_abi

#** install oh-my-zsh
[ ! -d "$ZSH" ] && sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

#** nodejs setup
asdf plugin add nodejs
asdf install nodejs latest
asdf global nodejs latest

#** pnpm setup
asdf plugin add pnpm
asdf install pnpm latest
asdf global pnpm latest
pnpm i -g @microsoft/rush vite vercel turbo

#** elixir setup
asdf plugin add erlang
asdf plugin add elixir
KERL_BUILD_DOCS=yes asdf install erlang latest
asdf install elixir latest
asdf global erlang latest
asdf global elixir latest

#** golang setup
asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
asdf install golang latest
asdf global golang latest
# go install .../golangci-lint@latest
# go install .../godoc@latest
# go install .../mockgen@latest
